import fs from 'node:fs';
import path from 'node:path';

// Load locale JSON generated by `tyndale translate`
export function loadTranslations(locale: string): Record<string, string> {
  if (locale === 'en') return {}; // English is the source — no translation needed
  const filePath = path.join(process.cwd(), 'public', '_tyndale', `${locale}.json`);
  try {
    return JSON.parse(fs.readFileSync(filePath, 'utf-8'));
  } catch {
    return {}; // Fallback: missing file = use English source text
  }
}

// Build a t() function for a given locale
export function createT(locale: string) {
  const translations = loadTranslations(locale);
  return (source: string): string => translations[source] ?? source;
}

// All supported locales (excluding default English)
export const supportedLocales = ['es', 'fr', 'de', 'pt', 'ja', 'ko', 'zh', 'it', 'ru'] as const;
